# Generated by Django 5.0 on 2023-12-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=12, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("mensagem", models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
