# Generated by Django 5.0 on 2023-12-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cliente_celular_cliente_endereco"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="email",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="endereco",
        ),
    ]
